import { IconButtonProps, DefaultButtonProps } from "./factory/buttonBase";
import CodepenIcon from "./factory/icons/CodepenIcon";
import DevToIcon from "./factory/icons/DevToIcon";
import DiscordIcon from "./factory/icons/DiscordIcon";
import FbIcon from "./factory/icons/FbIcon";
import GithubIcon from "./factory/icons/GithubIcon";
import LinkedinIcon from "./factory/icons/LinkedinIcon";
import MailIcon from "./factory/icons/MailIcon";
import RedditIcon from "./factory/icons/RedditIcon";
import { ITabProps } from "./factory/tabBase";
import { IBlogCardProps } from "./type/card";

export const socialMediaInfoList: IconButtonProps[] = [
  {
    id: "mail",
    url: "mailto:tungxk2908@gmail.com",
    icon: MailIcon,
  },
  {
    id: "linkedin",
    url: "https://www.linkedin.com/in/xuan-khoa-tu-nguyen-1a8927204/",
    icon: LinkedinIcon,
  },
  {
    id: "github",
    url: "https://github.com/khoaxuantu",
    icon: GithubIcon,
  },
  {
    id: "facebook",
    url: "https://www.facebook.com/xuankhoatu.nguyen/",
    icon: FbIcon,
  },
  {
    id: "discord",
    url: "https://discordapp.com/users/623530338869837825",
    icon: DiscordIcon,
  },
  {
    id: "reddit",
    url: "https://www.reddit.com/user/khoaxuantu",
    icon: RedditIcon,
  },
  {
    id: "dev-to",
    url: "https://dev.to/khoaxuantu",
    icon: DevToIcon,
  },
  {
    id: "codepen",
    url: "https://codepen.io/khoaxuantu",
    icon: CodepenIcon,
  },
];

export const navBtnInfoList: DefaultButtonProps[] = [
  {
    url: "/about",
    content: "About",
  },
  {
    url: "/blogs",
    content: "Blogs",
  },
  {
    url: "/projects",
    content: "Projects",
  },
  {
    url: "/contact",
    content: "Contact",
  },
];

export const worksInfoList: ITabProps[] = [
  {
    name: "Pixta Inc.",
    content: {
      title: "Fullstack Web Developer",
      company: "Pixta",
      time: "06/2023 - now",
      location: "Hanoi, Vietnam",
      description: [
        `Develop and maintain the backend system of PixtaStock.
          Analyze data, evaluate the effectiveness of features to improve
          and develop new features.`,
        `Work closely with the Japan product design team to maintain the web application for
          internal tools.`,
        `Provide technical support to resolve and monitor PixtaStock's issues reported
          by the customers.`,
        `Frequently used stacks: Ruby on Rails, React, NodeJS, MySQL, MongoDB, Docker, Kubernetes,
          AWS`,
        `Updating...`,
      ],
    },
  },
  {
    name: "Pegatron",
    content: {
      title: "Data Engineer Intern",
      company: "Pegatron",
      time: "02/2022 - 06/2022",
      location: "Taipei, Taiwan",
      description: [
        `Participated in the Shop Floor Information System (SFIS) development team,
                which processes the data to integrate it with Pegatron's manufacturing process
                among 7 global and 2 local factories.`,
        `Learned how to track and update the data flow, manage and develop
                databases via Oracle Database.`,
        `Contributed to the transformation and loading process in the ETL
                 and customer's report by retrieving the data into >30 forms.`,
      ],
    },
  },
  {
    name: "Techman Robot Inc.",
    content: {
      title: "Robotic Automation Engineering Trainee",
      company: "Techman",
      time: "06/2020 - 08/2020",
      location: "Taoyuan, Taiwan",
      description: [
        `Got training in practical robotic processing and functioning.
                 (Robotic arm, AI, IoT, Computer vision)`,
        `Developed the TM robotic automation project and presented the project
                  at the 2020 Taipei Industrial Automation Exhibition.`,
        `Won the First Prize in the Projects competition held by the company.`,
      ],
    },
  },
];

export const blogInfoDict: { [id: string]: IBlogCardProps } = {
  great_ytb_channels_1: {
    content_section: "Blogs",
    id: "great_ytb_channels_1",
    title: "Great Youtube Channels (Part 1)",
    brief_description: `I watch youtube a lot, and I make a list of youtube channels
I have watched that you may find interesting. Here is part 1 of my list...`,
    url: "/great_ytb_channels_1",
    file: "great_ytb_channels_1.md",
    date: new Date("Apr 26 2023 22:35:23 GMT+0800"),
  },
  great_ytb_channels_2: {
    content_section: "Blogs",
    id: "great_ytb_channels_2",
    title: "Great Youtube Channels (Part 2)",
    brief_description: `I watch youtube a lot, and I make a list of youtube channels
I have watched that you may find interesting. Here is part 2 of my list...`,
    url: "/great_ytb_channels_2",
    file: "great_ytb_channels_2.md",
    date: new Date("Apr 27 2023 13:30:59 GMT+0800"),
  },
  markdown_starter: {
    content_section: "Blogs",
    id: "markdown_starter",
    title: "Get started with Markdown",
    brief_description:
      "My markdown theme which is generated by React Markdown.",
    url: "/markdown_starter",
    file: "markdown_starter.md",
    date: new Date("Thu Mar 23 2023 23:10:33 GMT+0700"),
  },
  uncommon_javascript_notes: {
    content_section: "Blogs",
    id: "uncommon_javascript_notes",
    title: "Uncommon JavaScript Notes - The language",
    brief_description: `JavaScript is super complicated, like a pain in your ass.
Even when you are quite familiar with programming languages logics and concepts,
you still find it difficult to cover major aspects in JS.`,
    url: "/uncommon_javascript_notes",
    file: "uncommon_javascript_notes.md",
    date: new Date("Fri Jun 16 2023 23:02:26 GMT+0700"),
  },
  uncommon_javascript_notes_1: {
    content_section: "Blogs",
    id: "uncommon_javascript_notes_1",
    title: "Uncommon JavaScript Notes - Browser: Document, Events, Interfaces",
    brief_description: `One thing that make JavaScript weird to learn is
how it interacts with the browser DOM, how to control the events, the forms,
and how the resource is loaded.`,
    url: "/uncommon_javascript_notes_1",
    file: "uncommon_javascript_notes_1.md",
    date: new Date("Sun Sep 03 2023 11:13:44 GMT+0700"),
  },
  learn_from_react_bun_boilerplate: {
    content_section: "Blogs",
    id: "learn_from_react_bun_boilerplate",
    title: "What I learned after re-creating a React boilerplate",
    brief_description: `We can learn by re-creating something. This post is
about which things I discovered just by a React boilerplate.`,
    url: "/learn_from_react_bun_boilerplate",
    file: "react_bun_boilerplate.md",
    date: new Date("Sun Oct 22 2023 19:43:00 GMT+0700"),
  },
};

export const blogInfoList: { dictKey: string; date: string }[] = [
  { dictKey: "great_ytb_channels_1", date: "Apr 26 2023 22:35:23 GMT+0800" },
  { dictKey: "great_ytb_channels_2", date: "Apr 27 2023 13:30:59 GMT+0800" },
  { dictKey: "markdown_starter", date: "Thu Mar 23 2023 23:10:33 GMT+0700" },
  {
    dictKey: "uncommon_javascript_notes",
    date: "Fri Jun 16 2023 23:02:26 GMT+0700",
  },
  {
    dictKey: "uncommon_javascript_notes_1",
    date: "Sun Sep 03 2023 11:13:44 GMT+0700",
  },
  {
    dictKey: "learn_from_react_bun_boilerplate",
    date: "Sun Oct 22 2023 19:43:00 GMT+0700",
  },
];
